### PR TITLE
Add support for SYSTEM font

### PR DESCRIPTION
**Pull request by dobragab**
See #87.

### CODE REVIEW

**Comment by k4zmu2a** [comment]
Alright, so the things I want changed:
•	Move string include to pch
•	Ideally Winmenu font name should be an option. But it has different family name for search and use, why?
•	Save new option to registry
•	In gdrv::find_font
o	Remove unused variable system_charset
o	Set gdrv::fontCharset = DEFAULT_CHARSET in find_font
o	Japanese language is missing fontSizes set. It should use default sizes, I am yet to receive font size preferences for it.

**Comment by dobragab** [comment]
I addressed your comments (hopefully), except the registry option for font name. (The names being different was due to me testing the System font itself.)

How would you like to use Font Name option? Besides "System Font" option, or replacing it? Also, how would we determine sizes for that font, as you can see we need to use a different fontsize array for WinMenu.

**Comment by k4zmu2a** [comment]
My idea was to add new option on top of "System Font", something like “System Font Name”.
Keep the rest of the code as is; when SF is set, use SFN option value in find_font.
As the first step, use fontSizes_WinMenu for SFN fonts, some fonts will surely fit.
Later we can add custom font scaling factors option if it becomes truly necessary.

**Comment by dobragab** [comment]
Done!

**Comment by k4zmu2a** [comment]
Thank you, merged.

**Pull request merged**
