### PR TITLE
Minor performance optimizations

### PR DESCRIPTION
**Pull request by dobragab**
Add `/Ob2` and `/Ot` flags in Release on x86 and x64.

Reduce number of unnecessary `FreePlayedBlocks()` calls. Before this change, the main loop basically called it in every iteration. Call it only after "some time". See screenshots for improvement.

Before:
before

After:
after

I didn't observe any memory leak, and I believe it should be clearly visible if wav bits were never freed.

### CODE REVIEW

**Comment by k4zmu2a** [comment]
Optimizations are fine.
The idea with WaveMix is good, waveOutGetPosition is a costly call.
However, let’s not destroy WaveMix API, even if we are the only callers.
Instead, add ‘free blocks’ parameter to WaveMix::Pump, true by default.
Control it from main loop.

**Comment by dobragab** [comment]
Good idea, I made the changes you requested (and force pushed).

I named the variable controlling `FreePlayedBlocks()` as `performCleanup` to indicate that it isn't just a `free`, it's much more than that.

**Comment by k4zmu2a** [comment]
Design is ok now, but there is one problem - someTimeCounter is never zero at Sound::Idle.
Try some other achievable value, like 300.

**Comment by dobragab** [comment]
Nice catch! Fixed.

BTW this didn't cause any leaks for me, I don't exactly know why.

**Comment by k4zmu2a** [comment]
Thank you, merged.
No leaks because WaveMix is operating with pre allocated memory.

**Pull request merged**
