### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SirGamers**
Removed

A 

Bunch

Of 

spaces

like 

this

### CODE REVIEW

**Comment by k4zmu2a** [comment]
Those spaces are intentionally left there, no merge.

**Comment by RiedleroD** [comment]
if you're not merging it, why not close it too? Just a suggestion for clutter removal.

**Comment by k4zmu2a** [comment]
I will close it eventually.
I am leaving some time for the issue/PR author to close it themselves.
Or respond, add details, whatever else.

**Comment by k4zmu2a** [comment]
New lines should stay.
Before md reformat, they were even more pronounced.

**Pull request closed without merging**
