### PR TITLE
updated Icon_1.ico with 256x256 render for modern Windows using IcoFX

### PR DESCRIPTION
**Pull request by adambonneruk**
Hi K4zmu2a, I love your work! this PR is to update the embedded windows .ico file to support the modern/larger 256x256 format. Example here (left-to-right: current, new, and firefox for reference)

image

For your info, i'll outline the steps used to create this icon (per [my other repo](https://github.com/adambonneruk/space-cadet-pinball/tree/master/icon)):

1. Using [k4zmu2a's 192px](https://github.com/k4zmu2a/SpaceCadetPinball/blob/master/SpaceCadetPinball/Icon_192x192.png) icon .png file
2. Uploaded to AI resizer https://bigjpg.com/ with 4x resize (free mode) generating a 768px image
3. New [768px](https://github.com/adambonneruk/space-cadet-pinball/blob/master/icon/reference/768.png) image brought into Paint.net
4. Paint.net Steps:
    - Resize to 256px
    - Used blown-up original [48px](https://github.com/adambonneruk/space-cadet-pinball/blob/master/icon/reference/48.png) icon for placement and shadow details (saved as [48px-x4.png](https://github.com/adambonneruk/space-cadet-pinball/blob/master/icon/reference/48px-x4.png))
    - Created shadow
    - Exported as [.png](https://github.com/adambonneruk/space-cadet-pinball/blob/master/icon/256x256%20Icon.png)
Saved [.pdn](https://github.com/adambonneruk/space-cadet-pinball/blob/master/icon/256x256%20Icon%20Resize%20(using%20ai)%20Work.pdn) file for prosperity
5. IcoFX Steps:
    - Opened Icon_1.ico from k4mu2a
    - Added new 256px as 256x256 32bit with Alpha
    - Saved as [.ico](https://github.com/adambonneruk/space-cadet-pinball/blob/master/icon/pinball.ico)

My understanding is my accepting this PR will mean future compilations of your source into .exe format will automatically pick up and utilise these changes (really looking forward to 2.1.0 whenever it ships!).

__Note__: _this is my first ever public PR 🤞 I hope it's a worthy addition!_

thank you,
Adam

### CODE REVIEW

**Comment by k4zmu2a** [comment]
Here is a build after PR merge, for you to check if this new icon works as expected:
[SpaceCadetPinball_x86_V2.1.0Dev.zip](https://github.com/k4zmu2a/SpaceCadetPinball/files/12012743/SpaceCadetPinball_x86_V2.1.0Dev.zip)

This build is quite close to 2.1.0Rel, one might even call it RC)

**Comment by adambonneruk** [comment]
I've seen similar issues with the windows icon cache too, typically just renaming the .exe to something different will show you the correct icon as a quick workaround until it catches up/refreshes manually. I'm sure theres a way to reload the cache quickly but I havent figured that out just yet

You mention 265 in your reply I guess you meant 256 (i dont know what would happen if you tried to load a 265x265 icon!)

I'm really happy this idea works and is accepted! thanks

I've checked your exe and the icon works great, I'm unable to play the game with it though (using default pinball files and the x86 sdl files), load error here:

image

**Comment by k4zmu2a** [comment]
The adjusted icon works as indented, that is good news.
I was indeed talking about 256x256 icon (aka subj of this PR).
The game now uses somewhat fresh version of SDL, which I failed to include.
That RenderGeometryRaw call is for HW GUI renderer.
SW/HW GUI is a compile time option; older SDL version would have worked with SW GUI.
Here is the same build, but this time with all dependencies:
[SpaceCadetPinball_v2.0.1RC.zip](https://github.com/k4zmu2a/SpaceCadetPinball/files/12014560/SpaceCadetPinball_v2.0.1RC.zip)

You are very welcome.
Thanks to you, modern Windows users will have one less program with weird/outdated icon. 
This high DPI icon idea never occurred to me, I just applied classic icon and never thought about it again)

**Comment by adambonneruk** [comment]
> The adjusted icon works as indented, that is good news. I was indeed talking about 256x256 icon (aka subj of this PR). The game now uses somewhat fresh version of SDL, which I failed to include. That RenderGeometryRaw call is for HW GUI renderer. SW/HW GUI is a compile time option; older SDL version would have worked with SW GUI. Here is the same build, but this time with all dependencies: [SpaceCadetPinball_v2.0.1RC.zip](https://github.com/k4zmu2a/SpaceCadetPinball/files/12014560/SpaceCadetPinball_v2.0.1RC.zip)
> 
> You are very welcome. Thanks to you, modern Windows users will have one less program with weird/outdated icon. This high DPI icon idea never occurred to me, I just applied classic icon and never thought about it again)

FYI The file you attached looked even older (v2.0.1-rc e.g its missing the 256px icon) that the last one (v2.1.0-dev). I've tried lots of cominations of .exe and .dll with no luck

**Comment by k4zmu2a** [comment]
Yep, that was indeed some old RC build, foiled again by Win11 UI.
I was meaning to attach this build, sorry for the confusion:
[SpaceCadetPinball_x86_V2.1.0Dev.zip](https://github.com/k4zmu2a/SpaceCadetPinball/files/12121817/SpaceCadetPinball_x86_V2.1.0Dev.zip)

**Comment by adambonneruk** [comment]
works like a treat, nice one!

**Pull request merged**
