### PR TITLE
Add Linux installation info

### PR DESCRIPTION
**Pull request by NicolaSmaniotto**
Add a repology badge and mention the possibility to install via the package manager.

I believe this is a better approach than explicitly mentioning a repository, because it uses repology's database (and the list will remain updated).

### CODE REVIEW

**Comment by k4zmu2a** [comment]
I am ok with this idea.

Repo image placement in the On Windows section looks weird to me.
I’d rather have it in the On Linux section, with “Some distributions…” text positioned as annotation below the image.

**Comment by NicolaSmaniotto** [comment]
You are right, looking at the raw README it seems part of the On Windows section. I placed it there because once rendered (like github/gitlab do) the table is at the same height of the On Linux header.

The table can be put inside of the text removing the `align="right"`, but since it can (and hopefully will) grow quite long it seems a bad idea. An alternative would be to use just the repo count ([here](https://repology.org/project/spacecadetpinball/badges) are the options).

**Comment by k4zmu2a** [comment]
Having tried it, I see that is not as ok as I initially thought.
Right alignment causes the image to overflow the section(s) it is in; this is a no-go for me.
I can consider it, if the image can be confined to one section, depending on how it looks.
I don’t appreciate that section boundary break, it should not be used.

Overall, I prefer not to add extra complexity if possible.
So just go with the tiny badge displayed inline near new text.

**Comment by k4zmu2a** [comment]
Thank you, merged.

**Pull request merged**
