### PR TITLE
Add spaces to .desktop display name

### PR DESCRIPTION
**Pull request by LucyLikesYourFace**
Tiny change, think it looks better.
Feel free to remove this if disagree

### CODE REVIEW

**Comment by k4zmu2a** [comment]
This is fine by me, merged.

**Comment by NicolaSmaniotto** [comment]
Hi @k4zmu2a. With this merge there have been quite a few improvements for Linux, can we get a new release to package soon?

**Comment by k4zmu2a** [comment]
Sure, why not. It will 2.0.1 bugfix release.
But before that, I planned to release 1.2. Maybe I will do both if time permits.
Hobby programming time slice has been slim for me in the past couple of weeks.

**Comment by NicolaSmaniotto** [comment]
Thank you!

**Pull request merged**
