### PR TITLE
Add linux desktop file and install

### PR DESCRIPTION
**Pull request by NicolaSmaniotto**
In this PR:

1. Some of the images inside Icon_1.ico have been extracted and converted to png
2. A basic Linux desktop file has been added, which uses the new icons
3. Cmake adds an install phase, which copies the binary and installs the desktop file

All of this should only affect Linux systems, and from my tests works as intended. It should also help with packaging (see  #95), since right now maintainers have to manually move the executable.
Please note that although it is probably fine, I have not tested this on other operating systems.

### CODE REVIEW

**Comment by k4zmu2a** [comment]
Everything looks good to me, except for the icons.
I would like to use a higher quality 32-bit icon subset.
I think that 4-bit icons poorly represent the original 3DPB from XP.

3DPB icons

**Comment by k4zmu2a** [comment]
Thank you, merged.

**Comment by LucyLikesYourFace** [comment]
Not sure if this is the right place to discuss this, but where would one put the original  pinball data files when installed like this? I haven't been able to work this out myself.
 I am packaging this as .deb for my own use and would to make use of this.

**Comment by NicolaSmaniotto** [comment]
I'm not sure this is the right place either. We should probably update the README.

The game searches in the folder where the executable is, but a fallback for other user-writable folders has been added (see #80). It is not yet part of a release, so you have to build the current master or backport the commit to the 2.0 (like [this](https://gitweb.gentoo.org/repo/proj/guru.git/tree/games-arcade/SpaceCadetPinball/files/SpaceCadetPinball-2.0-respect-XDG_DATA_HOME.patch))

**Comment by LucyLikesYourFace** [comment]
I am building from master but did not know about this. is it only possible for per-user files or could a different system-wide folder be used?

**Comment by NicolaSmaniotto** [comment]
I think (see the [freedesktop specs](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)) the correct system-wide folder would be something like `/usr/share/SpaceCadetPinball` (if managed by the package manager), or `/usr/local/share/SpaceCadetPinball` (if managed by the user), but I'm not sure those directories are supported.

You should try to poke around a bit, and if it doesn't work open a relevant issue.

**Comment by k4zmu2a** [comment]
You don’t need my permission, discuss whatever wherever.
I did not enable discussions tab because I think issues offer enough room for now.

Personally, I find the idea of separating game data from executable strange.
But if somebody needs it, I am not against adding more data search paths.

As for readme, I think Linux-specific data locations could be described in Compiling On Linux section.

**Pull request merged**
