### PR TITLE
Russian translation overhaul

### PR DESCRIPTION
**Pull request by HarGabt**
Adding the [localisation feature](https://github.com/k4zmu2a/SpaceCadetPinball/commit/66a868083aa81b4a3710ac1b30d33226b603c703) is a welcome addition to this project - something I as a localiser had been excited for a long time. Alas, the strings introduced in this commit give the feeling of being google-translated. So...

Most of strings were renamed according to the official localisation (bundled with Russian WinXP distros, manual only), some of them I had to adapt myself.

Feel free to correct some of those strings and switch to Russian language in this conversation if needed.

### CODE REVIEW

**Comment by k4zmu2a** [comment]
It is about time someone with proper language background corrected my mess.

Russian texts you see were not in fact done using machine translation)
I added them as part of the first localization test in v1. At that time, it did not occur to me to read the chm for guidance.
Later, I considered wiping it in favor of authentic English texts used in Ru version but decided against it in the end.

The only concern I have about new texts is with “wormhole” == “норка”.
In my opinion, “червоточина” seems less ambiguous for a space-themed game.
Does this term come from the official chm?

I prefer English for public discussions about the project.

**Comment by HarGabt** [comment]
>Does this term come from the official chm?

<details>
  <summary>Picture behind a spoiler (Yes, it does come from the official .chm file)</summary>

изображение


</details>

Your choice is your choice to put `Червоточина` instead of `Норка`

**Comment by k4zmu2a** [comment]
Thank you, merged.

**Comment by win98se** [comment]
I think the translation improvements in here and also #156 can be merged into v1 as well.

**Pull request merged**
