### PR TITLE
Improve linux building

### PR DESCRIPTION
**Pull request by kowalski7cc**
This merge adds the following changes:
Move Linux related files in folder Platform/Linux
Change SpaceCadetPinball.desktop to reflect the original game name and description
Add a metainfo.xml file to support Appstream data
Add a new upscaled icon (at 192x192) that will be nicer in the launcher
Update readme.md with a brief description of the original game, and some instruction for building on Linux

### CODE REVIEW

**Comment by k4zmu2a** [comment]
I don’t like some of these changes:
In .destop:
Keep existing Name=Space Cadet Pinball.
Comment – I assume the comment is about application, not the desktop file. Keep existing comment.

No need to change the readme, especially project name.
Readme space is precious, more so at the top. All non-essential info should be at the very bottom or skipped.
I consider all but audio issue to be non-essential.
Audio issue has wording problems, it implies that music does not work without steps shown.

The rest is good to go.

If you really want to, put your readme in a separate PR, where we will deconstruct it more thoroughly.

**Comment by kowalski7cc** [comment]
For the .desktop file I was trying to mimic the Windows shortcut:
image

**Comment by k4zmu2a** [comment]
Mimicking something is fine, but I think having just “pinball” as a name is misleading.
I rather have specific project name used there.

**Comment by kowalski7cc** [comment]
@k4zmu2a I only left a couple of lines for who doesn't know what Space Cadet was. Also changed in desktop files to the name of the project

**Comment by k4zmu2a** [comment]
It is better now, but still does not fully satisfy my arbitrary standards :)

I want the old .desktop Comment back.
Maxis never published 3DBP, they had Full Tilt! Pinball. Also remove the newline.
Do not format source ports table.
Readme should not have specific commands, rather general advice. Remove the install/build section.

**Comment by kowalski7cc** [comment]
> Readme should not have specific commands, rather general advice. Remove the install/build section.
I do not fully agree. Especially people that approaches Linux usually doesn't know how to build from sources, so I added an example.

**Comment by kowalski7cc** [comment]
Other things changed

**Comment by NicolaSmaniotto** [comment]
If you want to create a Linux specific folder, we could move the .png icons there as well.

Also, for what is worth, I agree with @k4zmu2a about the commands in the readme. Compiling and installing from source (from a random github page) is not something an inexperienced user should do. A nicer approach would be to create and maintain packages in the correct repositories.

**Comment by kowalski7cc** [comment]
@NicolaSmaniotto I think other platforms could benefit from the icons.

For the readme, I've seen many with the commands, or at least with the correct name of the libs for a couple of platforms. Like Debian and Fedora tend to have very different naming for some libraries. An experienced user can just ignore it.

**Comment by NicolaSmaniotto** [comment]
I don't mean to sound rude or insistent, but I can't find a way to word this better:

> correct name of the libs for a couple of platforms

That's only interesting to distro maintainers. Users don't need that info, not in the readme.

> Debian and Fedora tend to have very different naming for some libraries

And it's the job of the maintainers to know the correct name for (just) their own.

> An experienced user can just ignore it.

In my mind they are the only ones who would try to compile it themselves.

I still believe that users should not be encouraged to install software without the package manager, as this can have pretty serious repercussions. This extra information about how to compile (and troubleshoot audio) is probably better suited for a dedicated `BUILD.md` file, maybe in the Linux specific folder.

**Comment by kowalski7cc** [comment]
I like the `BUILD.md` idea.

**Comment by kowalski7cc** [comment]
> I still believe that users should not be encouraged to install software without the package manager

Nor install packages maintained from unknown third parties... (I wonder how many people reads the PKGBUILD from AUR before installing). At that point probably building from GitHub doesn't sound so bad.
Also, the current readme encourages Linux users to build themself the binary, and the provided packages are already for distributions used by experienced people.

**Comment by k4zmu2a** [comment]
Merged, that you for your patience.

For obscure programs compiling from source is often the only universal way to run them.
To facilitate this, I tried to make the build as simple as possible.
Flatpak will be the first universal alternative, but that is not for everyone.

Separate in depth docs are fine with me, I already have some in /Doc.

**Comment by k4zmu2a** [comment]
One more thing, why would you use ninja generator in BUILD.md?
I think default makefile generator would make the build simpler.

**Comment by kowalski7cc** [comment]
It was suggested on the flathub submission that ninja builds faster. I don't know if it's placebo, but it seems faster on my i3

**Pull request merged**
